### ISSUE TITLE
-t option (timeout)

### ISSUE THREAD

**Issue by jlixfeld** [DjinnS/check-rbl#5]
Some of the rbl hosts are not responding while running the script.  I have taken to commenting them out of the list.  Would it be worth adding a -t option to specify a timeout (in ms) to wait for a response before considering the entry in the @rbl array dead and move on to the next one?

BlackBox-3:check-rbl-master jlixfeld$ grep "#'" check-rbl.pl
    #'dnsbl.njabl.org',
    #'relays.mail-abuse.org',
    #'rbl-plus.mail-abuse.org',
    #'combined.njabl.org',
    #'blackholes.mail-abuse.org',
    #'rot.blackhole.cantv.net',
    #'relays.bl.kundenserver.de',
    #'dul.blackhole.cantv.net',
BlackBox-3:check-rbl-master jlixfeld$

**Comment by DjinnS** [comment]
Hi,

"timeout" option is now available. Unfortunately it's in second because of the lib limitation.

https://github.com/DjinnS/check-rbl/commit/bc3714ab28693da8056736443722415ca568a5f2

**Comment by neuhaus** [comment]
Fractional seconds should work as the timeout if needed.
